---
- name: Create MySQL Table
  hosts: all
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
    mysql_db_name: "rbl_demo"
    mysql_script_name: "mysql_script.sql"
    mysql_validatation_query: "SELECT COUNT(*) FROM rbl_table;"
    rows_affected: 2
#  vars_files:
 #   - db_credentials.yml
  tasks:
    - name: DB creation Task
      mysql_db:
        name: "{{ mysql_db_name }}"
        state: present
        login_user: test
        login_password: 123
      register: db_creation_output

    - name: Print DB creation logs
      debug:
        var: db_creation_output

    - name: Copy sql script to target host
      ansible.builtin.copy:
        src: "{{ mysql_script_name }}"
        dest: /home/ansible
      
    - name: Insert Sample Data in to created DB - {{ mysql_db_name }}
      mysql_db:
        name: "{{ mysql_db_name }}"
        state: import
        target: "/home/ansible/{{ mysql_script_name }}"
        login_user: test
        login_password: 123
      register: db_import_logs

    - name: Print DB insert logs
      debug:
        var: db_import_logs

    - name: Validate data to ensure proper rows are affected
      mysql_query:
        login_db: "{{ mysql_db_name }}"
        query: "{{ mysql_validatation_query }}"
        login_user: test
        login_password: 123
      register: val_result
      failed_when: not val_result.query_result[0] is search("{{ rows_affected }}")
