---
- name: CRUD operation on MYSQL
  hosts: all
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Run several insert queries against db test_db in single transaction
      community.mysql.mysql_query:
        login_db: RBL
        query:
        - INSERT INTO apps(appid,name,ip) VALUES("{{ input }}")
        single_transaction: true
