---
- name: Insert operation on MYSQL
  hosts: all
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
#    - name: Copy sql script to target host
#      ansible.builtin.copy:
#        src: "{{ mysql_script_name }}"
#        dest: /home/ansible
      
    - name: Run several insert queries against RBL DB in single transaction
      mysql_db:
        name: RBL
        state: import
        target: /home/ec2-user/mysql_script.sql 
        login_user: test
        login_password: 123
      register: db_import_logs
